# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YROSbGqFG4wi1ojMSyRn2ZDfZaVuk5ic
"""

from jarvis_backend import new_session, ask_jarvis, extract_jarvis_params

import gradio as gr
from datetime import date, datetime
# …and your Jarvis imports…
# from your_notebook_module import new_session, ask_jarvis, extract_jarvis_params

session = new_session()

def respond(user_text, asset, as_of, chat_history):
    user_text = user_text.strip()
    low = user_text.lower()

    # 1) Goodbyes
    if low in ["bye","exit","quit","goodbye"]:
        farewell = "Goodbye! 👋"
        chat_history.append({"role":"user","content":user_text})
        chat_history.append({"role":"assistant","content":farewell})
        return chat_history, ""

    # 2) Update asset/date in session
    session["last_asset"] = asset
    try:
        session["last_date"] = datetime.fromisoformat(as_of).date()
    except:
        err = f"Sorry, '{as_of}' isn’t valid (YYYY-MM-DD)."
        chat_history.append({"role":"user","content":user_text})
        chat_history.append({"role":"assistant","content":err})
        return chat_history, ""

    # 3) Parse intent
    params = extract_jarvis_params(user_text)
    intent = params["intent"]

    # 4) Fallback → force forecast (unchanged)
    call_text = user_text
    if intent == "fallback" and asset and session["last_date"]:
        call_text = "forecast " + user_text

    # 5) Get answer
    answer = ask_jarvis(call_text, session)

    # 6) Append
    chat_history.append({"role":"user","content":user_text})
    chat_history.append({"role":"assistant","content":answer})
    return chat_history, ""

with gr.Blocks(theme=gr.themes.Default()) as demo:
    gr.Markdown("## 🚀 Jarvis: Your Financial Co-pilot")

    with gr.Row():
        asset_sel = gr.Dropdown(choices=["TSLA"], value="TSLA", label="Asset")
        date_sel  = gr.Textbox(value=date.today().isoformat(),
                              label="Date (YYYY-MM-DD)")

    chat = gr.Chatbot(label="Chat History", type="messages", height=500)

    with gr.Row():
        txt  = gr.Textbox(placeholder="Ask me about TSLA…", label="Your question")
        send = gr.Button("Send", variant="primary")

    with gr.Row():
        # <<< UPDATED pills block >>>
        pills = {
            "Forecast":       "Forecast next-day outlook for",
            "Reasoning":      "Explain prediction drivers for",
            "Recommend":      "Recommend buy/sell/hold for",
            "Deep-Sentiment": "Deep dive into sentiment for",
            "Deep-Technical": "Deep dive into RSI for",   # the fix!
            "Help":           "help"
        }

        for label, prefix in pills.items():
            btn = gr.Button(label, size="sm")
            if label == "Help":
                btn.click(lambda: "help",
                          inputs=None,
                          outputs=txt)
            else:
                def make_click(p):
                    return lambda a: f"{p} {a}"
                btn.click(make_click(prefix),
                          inputs=[asset_sel],
                          outputs=[txt])

    txt.submit(respond,
               inputs=[txt, asset_sel, date_sel, chat],
               outputs=[chat, txt])
    send.click(respond,
               inputs=[txt, asset_sel, date_sel, chat],
               outputs=[chat, txt])

demo.launch()