# -*- coding: utf-8 -*-
"""Jarvis_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aytMroUSO-EABMeJqlCWfi1kNZIWqyC
"""

# Cell 1 – JARVIS LLM Assistant: Intent Space
# ================================================================
INTENT_SPACE = [
    {
        "intent": "forecast",
        "aliases": [
            "what will happen", "forecast", "predict", "next day", "tomorrow",
            "future", "will TSLA go up", "direction", "price move"
        ],
        "description": "Predict next move, probability up/down, expected return."
    },
    {
        "intent": "reasoning",
        "aliases": [
            "why", "explain prediction", "top drivers", "reason", "shap", "influence"
        ],
        "description": "Explain why the model predicts that (SHAP, drivers)."
    },
    {
        "intent": "compare",
        "aliases": [
            "compare", "riskier", "vs", "versus", "better than", "relative",
            "which is safer", "which is more volatile"
        ],
        "description": "Compare two or more assets on risk, return, volatility, or model output."
    },
    {
        "intent": "trend",
        "aliases": [
            "trend", "how has", "performance", "recent returns", "history",
            "track record", "equity curve"
        ],
        "description": "Show performance/trend (recent, ytd, custom period)."
    },
    {
        "intent": "event",
        "aliases": [
            "news", "filing", "SEC", "events", "what happened", "headline",
            "catalyst", "impact"
        ],
        "description": "Show news or filings likely to have impacted the asset."
    },
    {
        "intent": "recommend",
        "aliases": [
            "recommend", "buy", "sell", "hold", "should I", "advice"
        ],
        "description": "Give a buy/sell/hold recommendation with reasoning."
    },
    {
        "intent": "help",
        "aliases": [
            "help", "what can you do", "capabilities", "features"
        ],
        "description": "List Jarvis assistant capabilities."
    },
    {
        "intent": "fallback",
        "aliases": [
            "unknown", "unrecognized", "confused", "error"
        ],
        "description": "Handle unrecognized or unclear queries."
    },

    # ─── New “Deep Dive” Intents ──────────────────────────────
    {
        "intent": "deep_sentiment",
        "aliases": [
            "deep dive sentiment", "sentiment deep dive", "dig into sentiment",
            "news tone", "social buzz", "detailed sentiment"
        ],
        "description": "Provide a detailed breakdown of news & social‐media sentiment."
    },
    {
        "intent": "deep_technical",
        "aliases": [
            "deep dive technical", "technical deep dive", "dig into indicators",
            "RSI deep dive", "MACD deep dive", "volatility deep dive"
        ],
        "description": "Provide a detailed breakdown of technical indicators (RSI, MACD, ATR, etc.)."
    },
    {
        "intent": "deep_sec",
        "aliases": [
            "deep dive filings", "filings deep dive", "SEC deep dive",
            "10-K deep dive", "10-Q deep dive", "CAR deep dive"
        ],
        "description": "Provide a detailed breakdown of SEC filing impacts (FinBERT, CAR, p-values)."
    },
]

print(f"Loaded JARVIS intent space ({len(INTENT_SPACE)} types):")
for intent in INTENT_SPACE:
    print(f" • {intent['intent']} – {intent['description']}")

# ================================================================
# Cell 2 – Reasoning Context Structure (cell_llm_2_context)
# ================================================================

# A single template capturing every piece of data Jarvis may need.
# Fill each field from your pipelines (or leave as None/"N/A" if missing).

CONTEXT_TEMPLATE = {
    # 1) Basic query info
    "asset":            None,    # e.g. "TSLA"
    "as_of_date":       None,    # e.g. "2025-07-01" (ISO string or date)
    "intent":           None,    # e.g. "forecast", "deep_sentiment", etc.
    "user_query":       None,    # raw text

    # 2) Model predictions
    "prediction": {
        "expected_return": None,  # float, e.g. 0.025 for +2.5%
        "prob_up":         None,  # float ∈ [0,1]
        "prob_down":       None,  # float = 1 - prob_up
        "prob_bigmove":    None,  # float
        "confidence":      None,  # float = max(prob_up,prob_down) - 0.5
    },

    # 3) SHAP / driver reasoning
    "reasoning": {
        "top_drivers": [],        # List[str], e.g. ["return_pct_t1:-0.0488", …]
        "shap_values": {}         # Dict[str,float] full feature→SHAP map
    },

    # 4) Recent news & social sentiment
    "news_events": [],           # List[{"date":str,"headline":str,"source":str,"sentiment":…}, …]
    "social_sentiment": {
        "reddit_score":      None,  # aggregate daily
        "stocktwits_score":  None,
        "post_count":        None
    },

    # 5) SEC 10-K / 10-Q filings
    "sec_filings": [],           # List[{"date":str,"form":str,"FinBERT":float,"CAR_0_2":float,"p_value":float,"summary":str}, …]

    # 6) Technical & macro indicators
    "technical": {
        "rsi_14":    None,    # 14-day RSI
        "rv20":      None,    # realized vol
        "macd":      None,    # MACD value
        "atr_14":    None,    # ATR
        "sma_20":    None     # simple moving average
    },
    "macro": {
        "vix_ret":   None,    # VIX return prior day
        "qqq_ret":   None,
        "nvda_ret":  None     # peer move
    },

    # 7) Recent performance / backtest trend
    "trend": {
        "last_5d_returns":   [],     # List[float]
        "equity_curve_csv":  None    # path to backtest_equity_reg.csv
    },

    # 8) Meta / provenance / caveats
    "meta": {
        "model_name":        None,    # e.g. "xgb_reg_v1"
        "data_as_of":        None,    # timestamp of data snapshot
        "feature_snapshot":  {},      # Dict[str,float] of key features at date
        "caveats":           []       # List[str], e.g. ["Model trained up to …"]
    }
}

# Example usage: make a working copy for today’s query
# context = deepcopy(CONTEXT_TEMPLATE)
# context["asset"] = "TSLA"
# context["as_of_date"] = "2025-07-01"
# …etc.


# ──────────────────────────────────────────────────────────────────────────
# Cell 3 – Intent / Asset / Date Parsing (UPDATED)
# ──────────────────────────────────────────────────────────────────────────

import re
import dateparser
from dateparser.search import search_dates
import pandas as pd

# 1) Intent → Keywords map

INTENT_KEYWORDS = {
    "forecast":    [ "forecast", "predict", "outlook", "next", "tomorrow",
                     "future", "will tsla go up", "direction", "price move" ],
    "reasoning":   [ "why", "reason", "explain", "driver", "shap" ],
    "compare":     [ "compare", "vs", "versus", "relative" ],
    "trend":       [ "trend", "performance", "recent", "history", "ytd" ],
    "event":       [ "news", "event", "filing", "sec", "headline" ],
    "explain":     [ "what is", "help", "define", "meaning", "how" ],
    "recommend":   [ "recommend", "should i", "buy", "sell", "hold" ],
    "deep_sentiment":  [ "sentiment", "news tone", "social buzz" ],
    "deep_technical":  [
        "rsi", "volatility", "atr", "momentum", "macd",
        "technical", "technicals",     # ← newly added
        "deep dive technical",         # ← newly added
        "technical deep dive"          # ← newly added
    ],
    "deep_sec":    [ "filing", "10-k", "10-q", "car", "finbert" ],
    "help":        [ "help", "capabilities", "usage", "what can" ],
    "greeting":    [ "hi", "hello", "hey", "good morning", "good afternoon" ],
    # fallback has no keywords
    "fallback":    []
}



# 2) Asset synonyms → Ticker
TICKER_MAP = {
    "tsla":  "TSLA",
    "tesla": "TSLA",
    # add more later...
}

def extract_jarvis_params(user_query: str):
    """
    Parses a user's query into:
      - intent: one of INTENT_KEYWORDS keys or 'fallback'
      - asset: ticker symbol (e.g. 'TSLA') or None
      - date: datetime.date or None
      - aspect: for deep dives ('sentiment','technical','sec') or None
    """
    q = user_query.lower()
    params = {"intent": "fallback", "asset": None, "date": None, "aspect": None}

    # 1) Greeting → immediate
    for kw in INTENT_KEYWORDS["greeting"]:
        if kw in q:
            params["intent"] = "greeting"
            return params

    # 2) Intent matching (first match wins)
    for intent, kws in INTENT_KEYWORDS.items():
        if intent == "greeting":
            continue
        if any(kw in q for kw in kws):
            params["intent"] = intent
            break

    # 3) Asset detection
    for name, ticker in TICKER_MAP.items():
        if name in q:
            params["asset"] = ticker
            break

    # 4) Date detection
    if "today" in q:
        params["date"] = pd.Timestamp("today").date()
    elif "tomorrow" in q:
        params["date"] = (pd.Timestamp("today") + pd.Timedelta(days=1)).date()
    else:
        found = search_dates(user_query, settings={"PREFER_DATES_FROM": "future"})
        if found:
            params["date"] = found[0][1].date()

    # 5) Aspect for deep dives
    if params["intent"].startswith("deep_"):
        params["aspect"] = params["intent"].split("_", 1)[1]

    return params

# ========= FEATURE EXPLANATION MAPPING ==========
FEATURE_EXPLAIN = {
    "return_pct_t1": "Recent price momentum (yesterday’s return)",
    "rv20": "20-day realized volatility (market risk)",
    "macd": "Momentum from MACD indicator",
    "macd_hist": "MACD signal strength",
    "sma_5": "5-day moving average",
    "ema_10": "10-day exponential moving average",
    "bollinger_z": "Distance from Bollinger Bands (overbought/oversold)",
    "news_sentiment_master": "Overall news sentiment",
    "FinBERT_score_sec": "Sentiment in latest SEC filings",
    # Add more feature explanations as your pipeline uses them
}

def link_drivers_to_news(top_drivers, feature_explain, news_list):
    linked = []
    for driver in top_drivers:
        expl = feature_explain.get(driver, driver)
        driver_words = set(expl.lower().replace("(", "").replace(")", "").split())
        matches = []
        for n in news_list:
            n_words = set(n.lower().split())
            if driver_words & n_words:  # intersection
                matches.append(n)
        linked.append((driver, expl, matches))
    return linked

def drivers_to_narrative(linked_drivers):
    lines = []
    for driver, expl, news_matches in linked_drivers:
        if news_matches:
            lines.append(f"{expl} — related news: “{news_matches[0]}”.")
        else:
            lines.append(f"{expl} was a key factor.")
    return " ".join(lines)

# ────────────────────────────────────────────────────────────────
# Cell 4 – Gather Context for LLM Answer
# ────────────────────────────────────────────────────────────────
import os, joblib, pandas as pd, numpy as np
from datetime import datetime

# Configuration
MODEL_DIR   = "/content/jarvis_models/tsla_v1"
FEATURE_CSV = "TSLA_master_daily_features_lag1.csv"

# 1) Load models & feature-lists
reg_model       = joblib.load("xgb_reg.pkl")
cls_model       = joblib.load("xgb_cls.pkl")
bigmove_model   = joblib.load("xgb_bigmove.pkl")
reg_features    = joblib.load("feature_list_reg.pkl")
cls_features    = joblib.load("feature_list_cls.pkl")
bigmove_features= joblib.load("feature_list_big.pkl")

# 2) Optional: precomputed SHAP top drivers
try:
    shap_reg_top = pd.read_csv("shap_reg_top.csv")
except FileNotFoundError:
    shap_reg_top = None

# 3) Load master feature table
feat_df = pd.read_csv(FEATURE_CSV, parse_dates=["date"])
feat_df["date"] = feat_df["date"].dt.date

def get_jarvis_context(asset: str, date_query: str) -> dict:
    """
    Returns all fields Jarvis needs for {asset} at {date_query}.
    """
    # a) align to last available trading date
    dq = pd.to_datetime(date_query).date()
    av = sorted(feat_df["date"].unique())
    if dq not in av:
        past = [d for d in av if d <= dq]
        if not past:
            return {"error": f"No data available for {date_query} or earlier."}
        dq = max(past)
    row = feat_df.loc[feat_df["date"] == dq].iloc[0]

    # b) Predictions
    Xr = pd.DataFrame([row[reg_features].to_dict()])
    Xc = pd.DataFrame([row[cls_features].to_dict()])
    Xb = pd.DataFrame([row[bigmove_features].to_dict()])

    pred_return = float(reg_model.predict(Xr)[0])
    cls_p       = cls_model.predict_proba(Xc)[0]
    prob_up     = float(cls_p[1]) if len(cls_p)>1 else 1.0 - float(cls_p[0])
    prob_down   = 1.0 - prob_up
    big_p       = bigmove_model.predict_proba(Xb)[0]
    prob_bigmove= float(big_p[1]) if len(big_p)>1 else float(big_p[0])

    # c) Direction for summary
    direction = "upward" if pred_return > 0 else "downward"

    # d) Top drivers
    drivers = shap_reg_top.head(5)["feature"].tolist() if shap_reg_top is not None else []

    # e) News list
    raw  = row.get("summary", "")
    news = raw.split("||") if isinstance(raw, str) and raw else []

    # f) Assemble
    context = {
        "asset":            asset,
        "as_of_date":       dq.isoformat(),
        "close_price":      row.get("close_price", 0.0),
        "pred_return":      pred_return,
        "prob_up":          prob_up,
        "prob_down":        prob_down,
        "prob_bigmove":     prob_bigmove,
        "direction":        direction,
        "drivers":          drivers,
        "news":             news,
        "sentiment_score":  row.get("sentiment_score", 0.0),
        "social_sentiment": row.get("social_sentiment_weighted_mean", 0.0),
        "social_volume":    row.get("social_posts_total", 0.0),
        "sec_finbert":      row.get("FinBERT_score_sec", 0.0),
        "sec_car02":        row.get("CAR_0_2_sec", 0.0),
        "sec_pvalue":       row.get("CAR_pvalue_sec", 0.0),
        "sec_days_ago":     row.get("days_since_sec", 0.0),
        "rsi_14":           row.get("rsi_14", 0.0),
        "rv20":             row.get("rv20", 0.0),
        "atr_14":           row.get("atr_14", 0.0),
        "macd":             row.get("macd", 0.0),
        "macd_signal":      row.get("macd_signal", 0.0),
        "bollinger_z":      row.get("bollinger_z", 0.0),
        "vix_ret":          row.get("vix_ret", 0.0),
        "qqq_ret":          row.get("qqq_ret", 0.0),
        "nvda_ret":         row.get("nvda_ret", 0.0),
    }
    return context

# ──────────────────────────────────────────────────────────────
# Cell 4 (append this)
# ──────────────────────────────────────────────────────────────

# 1) Which raw context keys each intent actually needs:
FIELDS_BY_INTENT = {
    "forecast":      ["pred_return","prob_up","prob_down","prob_bigmove",
                      "drivers","sentiment_score","sec_finbert","sec_car02",
                      "sec_days_ago","rsi_14","rv20","atr_14","vix_ret","nvda_ret"],
    "reasoning":     ["pred_return","drivers","sentiment_score","rsi_14","rv20"],
    "recommend":     ["pred_return","prob_up","drivers","sentiment_score","rv20"],
    "deep_sentiment":["sentiment_score","social_sentiment","social_volume","news"],
    "deep_technical":["rsi_14","rv20","atr_14","macd","macd_signal","bollinger_z"],
    "deep_sec":      ["sec_finbert","sec_car02","sec_pvalue","sec_days_ago"],
    "compare":       [],  # handled separately
    "trend":         [],  # handled separately
    "event":         [],  # handled separately
    "help":          [],
    "fallback":      []
}

def prune_context(raw_ctx: dict, intent: str) -> dict:
    """
    Keep only the fields FIELDS_BY_INTENT[intent], plus asset & as_of_date.
    """
    fields = FIELDS_BY_INTENT.get(intent, [])
    ctx = {
        "asset":      raw_ctx["asset"],
        "as_of_date": raw_ctx["as_of_date"],
    }
    for f in fields:
        v = raw_ctx.get(f)
        if v is not None:
            ctx[f] = v
    # always include any list‐valued drivers/news
    if intent in ("deep_sentiment","deep_technical","deep_sec"):
        ctx["news"]    = raw_ctx.get("news", [])
        ctx["drivers"] = raw_ctx.get("drivers", [])
    return ctx

# ────────────────────────────────────────────────────────────────
# Cell 5 – Prompt Engineering: Templates + build_prompt
# ────────────────────────────────────────────────────────────────
SYSTEM_MESSAGE = (
    "You are Jarvis, a friendly financial co-pilot.  "
    "Use the data provided to craft clear, concise bullet-point summaries in plain English.  "
    "Always end with “Anything else I can help you with?”"
)

# 1) Full‐summary / forecast
FORECAST_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Full summary for {asset} on {as_of_date}.

Please deliver **7 short bullets**:
1. **Closing price:** ${close_price:.2f}.
2. **Forecast:** predicted next-day return is {pred_return:.2%}, with a {prob_up:.1%}/{prob_down:.1%} up/down chance.
3. **Big-move chance:** {prob_bigmove:.1%}.
4. **Top driver:** {drivers}.
5. **News headlines:** {news}.
6. **Sentiment score:** {sentiment_score:.2f}.
7. **Technicals & peers:** RSI-14 {rsi_14:.1f}, RV20 {rv20:.2f}, ATR-14 {atr_14:.2f}, VIX {vix_ret:.2%}, NVDA {nvda_ret:.2%}.

Answer:
"""

# 2) Reasoning / “factors impacting price”
REASONING_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Factors impacting price for {asset} on {as_of_date}.

Please deliver **4 short bullets**:
1. **Overall prediction:** expected return {pred_return:.2%} → {direction} move.
2. **Top driver:** {drivers}.
3. **Sentiment & news:** score {sentiment_score:.2f}, headlines: {news}.
4. **Technicals & peers:** RSI-14 {rsi_14:.1f}, RV20 {rv20:.2f}.

In summary, these factors suggest a {direction} price movement.

Answer:
"""





# 3) Buy/Sell/Hold recommendation
RECOMMEND_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Buy/Sell/Hold recommendation for {asset} on {as_of_date}.

Please deliver **3 short bullets**:
• **Recommendation:** Buy, Sell, or Hold—and why.
• **Key driver:** {drivers} → plain meaning.
• **Risk note:** mention one caveat (volatility, news, SEC).

Answer:
"""

# 4) Deep-dive into sentiment
DEEP_SENTIMENT_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Deep-dive into **sentiment** for {asset} on {as_of_date}.

Please deliver **3 short bullets**:
• **News sentiment ({sentiment_score:.2f}):** what it implies.
• **Social buzz ({social_volume} posts at {social_sentiment:.2f}):** interpretation.
• **Headlines:** {news}

Answer:
"""

# 5) Deep-dive into technicals
DEEP_TECHNICAL_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Deep-dive into **technicals** for {asset} on {as_of_date}.

Please deliver **3 short bullets**:
• **RSI-14 ({rsi_14:.1f}):** what overbought/oversold means.
• **MACD ({macd:.2f} vs signal {macd_signal:.2f}):** momentum implication.
• **ATR-14 ({atr_14:.2f}):** typical daily move magnitude.

Answer:
"""

# 6) Deep-dive into SEC filings
DEEP_SEC_PROMPT = """
Date: {as_of_date}
Asset: {asset}

User wants: Deep-dive into **SEC filings** for {asset} on {as_of_date}.

Please deliver **2 short bullets**:
• **FinBERT tone ({sec_finbert:.2f}):** plain meaning.
• **CAR(0–2) ({sec_car02:.2%}, p-value {sec_pvalue:.3f}):** event significance.

Answer:
"""

# 7) Concept-explain (e.g. “what does RSI mean?”)
EXPLAIN_PROMPT = """

User wants: Explain the concept:
“{user_question}”

Please deliver **2 bullets**:
• A clear definition in plain English.
• Why this metric matters for price movements.

Answer:
"""

# 8) (other templates unchanged…)
COMPARE_PROMPT  = """…"""
TREND_PROMPT    = """…"""
EVENT_PROMPT    = """…"""
HELP_PROMPT     = """…"""
FALLBACK_PROMPT = """Sorry, I didn’t understand that. …"""

# 9) Assemble
PROMPTS = {
    "forecast":       FORECAST_PROMPT,
    "reasoning":      REASONING_PROMPT,
    "recommend":      RECOMMEND_PROMPT,
    "deep_sentiment": DEEP_SENTIMENT_PROMPT,
    "deep_technical": DEEP_TECHNICAL_PROMPT,
    "deep_sec":       DEEP_SEC_PROMPT,
    "explain":        EXPLAIN_PROMPT,
    "compare":        COMPARE_PROMPT,
    "trend":          TREND_PROMPT,
    "event":          EVENT_PROMPT,
    "help":           HELP_PROMPT,
    "fallback":       FALLBACK_PROMPT,
}

def build_prompt(intent: str, context: dict) -> str:
    tmpl = PROMPTS.get(intent, PROMPTS["fallback"])
    try:
        return tmpl.format(**context)
    except KeyError as e:
        return f"[Prompt error: missing {e}] Context:\n{context}"



# Commented out IPython magic to ensure Python compatibility.
# (removed: an OpenAI API key was hard-coded here in the original notebook export; it has been revoked/redacted)

# ================================================================
# Cell 6 – LLM Backend Integration + Logging (OpenAI API v1+)
# ================================================================

# 1) Install & import

import os
import time
import openai
from datetime import datetime

# 2) Configure your OpenAI API key
openai.api_key = os.getenv("OPENAI_API_KEY")
if not openai.api_key:
    raise RuntimeError("Please set OPENAI_API_KEY in your environment.")


# 3) LLM call function
def call_llm(prompt: str,
             system_message: str = SYSTEM_MESSAGE,
             model: str = "gpt-3.5-turbo",
             temperature: float = 0.2,
             max_tokens: int = 400,
             log_path: str = "jarvis_llm_log.csv") -> str | dict:
    """
    Sends a single user prompt (with a SYSTEM_MESSAGE) to the OpenAI ChatCompletion API,
    returns the assistant response as a string, or {'error': ...} on failure.
    Logs timestamp, model, prompt snippet, and response/error to CSV.
    """
    # Prepare log entry
    log_row = {
        "timestamp": datetime.utcnow().isoformat(),
        "model": model,
        "temperature": temperature,
        "prompt": prompt.replace("\n", "\\n")[:2000],
        "response": "",
        "error": ""
    }

    messages = [
        {"role": "system", "content": system_message},
        {"role": "user",   "content": prompt}
    ]

    try:
        resp = openai.chat.completions.create(
            model= model,
            messages= messages,
            temperature= temperature,
            max_tokens= max_tokens,
        )
        answer = resp.choices[0].message.content.strip()
        log_row["response"] = answer.replace("\n", "\\n")
        return answer

    except Exception as e:
        log_row["error"] = str(e)
        return {"error": str(e)}

    finally:
        # Write header if needed
        write_header = not os.path.exists(log_path)
        with open(log_path, "a", encoding="utf-8") as f:
            if write_header:
                f.write(",".join(log_row.keys()) + "\n")
            # quote values, remove any stray quotes
            row = []
            for v in log_row.values():
                clean = str(v).replace('"', '')
                row.append(f'"{clean}"')
            f.write(",".join(row) + "\n")

# --- Usage example (after STEP 5) ---
# prompt = build_prompt("forecast", context)
# response = call_llm(prompt)
# if isinstance(response, dict) and "error" in response:
#     print("LLM error:", response["error"])
# else:
#     print("LLM answer:\n", response)b

# ──────────────────────────────────────────────────────────────────────────
# Cell 7 – Conversational Loop: ask_jarvis() + Demo (UPDATED)
# ──────────────────────────────────────────────────────────────────────────

session = None  # will be initialized below

def new_session():
    return {
        "history":        [],      # last 5 turns
        "last_asset":     None,
        "last_date":      None,
        "last_intent":    None,
        "retry_asset":    0,
        "retry_date":     0,
        "retry_llm":      0,
        "apology_count":  0,
    }

def ask_jarvis(user_query: str, session: dict) -> str:
    q   = user_query.strip()
    low = q.lower()

    # 0) Exit handling
    if low in ["bye", "exit", "quit", "goodbye"]:
        return "Goodbye! 👋"

    # 1) Parse
    params = extract_jarvis_params(q)
    intent = params["intent"]
    asset  = params.get("asset") or session["last_asset"]
    date   = params.get("date")  or session["last_date"]

    # 2) Greeting
    if intent == "greeting":
        session["apology_count"] = 0
        reply = "Hello! What asset and date can I help you with today? Anything else I can help you with?"
        session["history"].append({"role":"assistant","content":reply})
        return reply

    # 3) Missing asset → retry
    if not asset:
        session["retry_asset"] += 1
        reply = (
            "I’m sorry, which asset would you like me to look up? (e.g., TSLA)"
            if session["retry_asset"] <= 2
            else "I’m still confused on the asset—type “help” to see how I can assist."
        )
        session["history"].append({"role":"assistant","content":reply})
        return reply
    session["last_asset"] = asset
    session["retry_asset"] = 0

    # 4) Missing date → retry
    if not date:
        session["retry_date"] += 1
        reply = (
            "I’m sorry, what date should I fetch the data for? (e.g., ‘2025-07-01’)"
            if session["retry_date"] <= 2
            else "Still not sure on the date—type it in YYYY-MM-DD or say “help.”"
        )
        session["history"].append({"role":"assistant","content":reply})
        return reply
    session["last_date"] = date
    session["retry_date"] = 0

    # 5) Gather context
    context = get_jarvis_context(asset, date_query=str(date))
    if "error" in context:
        reply = f"Sorry, {context['error']}."
        session["history"].append({"role":"assistant","content":reply})
        return reply

    # 6) Inject & sanitize
    context["asset"] = asset
    for k in [
        "pred_return","prob_up","prob_down","prob_bigmove",
        "sentiment_score","social_sentiment","social_volume",
        "sec_finbert","sec_car02","sec_pvalue","sec_days_ago",
        "rsi_14","rv20","atr_14","macd","macd_signal","bollinger_z",
        "vix_ret","qqq_ret","nvda_ret"
    ]:
        context[k] = context.get(k) or 0.0
    context["drivers"] = ", ".join(context.get("drivers", [])) or "N/A"
    context["news"]    = "; ".join(context.get("news", []))    or "No major events"

    # 7) Build prompt
    prompt = build_prompt(intent, context)

    # 8) Call LLM (with up to 2 retries)
    answer = None
    for _ in range(2):
        llm_out = call_llm(prompt)
        if isinstance(llm_out, dict) and "error" in llm_out:
            session["retry_llm"] += 1
            apology = "I’m sorry—something went wrong. Let me try again."
            answer = apology
            if session["retry_llm"] >= 2:
                answer = (
                    "I’m really sorry I can’t fetch a fresh answer right now. "
                    f"Here’s what I know so far: return={context['pred_return']:.2%}, "
                    f"up={context['prob_up']:.1%}, down={context['prob_down']:.1%}."
                )
            continue
        else:
            answer = llm_out
            session["retry_llm"] = 0
            break

    # 9) Closing
    if not answer.strip().endswith("Anything else I can help you with?"):
        answer += "\n\nAnything else I can help you with?"

    # 10) History
    session["history"].append({"role":"user",      "content":q})
    session["history"].append({"role":"assistant", "content":answer})
    session["history"] = session["history"][-5:]

    return answer